services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cnake_charmer
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cnake_charmer"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # PgAdmin - PostgreSQL Administration
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  # Redis Commander - Redis UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  worker:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://user:password@db/cnake_charmer"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      OPENROUTER_API_KEY: "${OPENROUTER_API_KEY}"
    # Fix the Celery worker command to point to the correct module
    command: celery -A cnake_charmer.generate.worker.worker.app worker --loglevel=info

  fastapi:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://user:password@db/cnake_charmer"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      OPENROUTER_API_KEY: "${OPENROUTER_API_KEY}"
    command: uvicorn cnake_charmer.generate.fastapi_service.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
      
  # Flower - Celery monitoring tool
  flower:
    build: .
    depends_on:
      - redis
      - worker
    environment:
      DATABASE_URL: "postgresql://user:password@db/cnake_charmer"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    # Fix the Flower command to point to the correct module
    command: celery -A cnake_charmer.generate.worker.worker.app flower --port=5555
      
volumes:
  postgres_data: