"""Flip generated byte-image rows and convert pixels to normalized values.

Adapted from The Stack v2 Cython candidate:
- blob_id: 1846657d33ecd757445eefdf38ac496f4535ef10
- filename: converter.pyx

Keywords: image_processing, bytes, row flip, pixel normalization, checksum
"""

from cnake_data.benchmarks import python_benchmark


@python_benchmark(args=(256, 192, 3))
def stack_byte_flip_convert(width: int, height: int, channels: int) -> tuple:
    """Generate an image byte buffer, vertical-flip it, and summarize normalized output."""
    size = width * height * channels
    state = 2463534242
    data = bytearray(size)
    for i in range(size):
        state = (1664525 * state + 1013904223) & 0xFFFFFFFF
        data[i] = (state >> 16) & 0xFF

    row_size = width * channels
    flipped = bytearray(size)
    out = 0
    for y in range(height):
        src = (height - 1 - y) * row_size
        dst = y * row_size
        for j in range(row_size):
            b = data[src + j]
            flipped[dst + j] = b
            out += b

    checksum = 0
    for i, b in enumerate(flipped):
        checksum = (checksum + ((i + 1) * b)) & 0xFFFFFFFF

    return (out, flipped[0], flipped[-1], checksum)
