#!/usr/bin/env python3
import os
import sys
import json
import shutil
import tempfile
import subprocess
import time
import signal
import argparse
import logging
import re
from pathlib import Path

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler()],
)
logger = logging.getLogger("cython-worker")

# Directory to watch for new job files
JOB_DIRECTORY = "/app/jobs"
OUTPUT_DIRECTORY = "/app/results"
POLLING_INTERVAL = 5  # seconds


def analyze_cython_efficiency(code):
    """Analyze Cython code for inefficient operations manually"""
    yellow_lines = []
    red_lines = []

    # Split code into lines
    lines = code.split("\n")

    for i, line in enumerate(lines):
        line_num = i + 1

        # Skip empty lines and comments
        if not line.strip() or line.strip().startswith("#"):
            continue

        # Yellow flag patterns (potentially slow)
        yellow_patterns = [
            r"isinstance\(",  # Type checking
            r"\.append\(",  # Python list operations
            r"\.extend\(",  # Python list operations
            r"\.pop\(",  # Python list operations
            r"\.keys\(",  # Dictionary operations
            r"\.values\(",  # Dictionary operations
            r"\.items\(",  # Dictionary operations
            r"numpy",  # NumPy usage (could be optimized)
            r"np\.",  # NumPy shorthand
            r"\[.+\]",  # List access
            r"lambda",  # Lambda functions
            r"list\(",  # List conversion
            r"dict\(",  # Dict conversion
            r"str\(",  # String conversion
        ]

        # Red flag patterns (very inefficient)
        red_patterns = [
            r"eval\(",  # Eval usage
            r"exec\(",  # Exec usage
            r"globals\(",  # Global namespace
            r"locals\(",  # Local namespace
            r"getattr\(",  # Dynamic attribute access
            r"setattr\(",  # Dynamic attribute setting
            r"import ",  # Import within function
            r"except",  # Exception handling
            r"try:",  # Try blocks
            r"re\.",  # Regular expressions
            r"json\.",  # JSON operations
            r"random\.",  # Random operations
            r"class ",  # Class definitions within functions
            r"__.*__",  # Dunder methods
        ]

        # Check for yellow patterns
        for pattern in yellow_patterns:
            if re.search(pattern, line):
                yellow_lines.append((line_num, line.strip()))
                break

        # Check for red patterns
        for pattern in red_patterns:
            if re.search(pattern, line):
                red_lines.append((line_num, line.strip()))
                break

    return yellow_lines, red_lines


def parse_cython_html(html_content, hot_ranges=None, ignore_imports=True):
    """
    Parse Cython annotation HTML and bucket source lines by "lower-is-better" scores.

    Args:
        html_content (str): The HTML content generated by Cython's annotate option.
        hot_ranges (list of (int,int), optional): Line-number ranges to focus on, e.g. [(21,78)].
        ignore_imports (bool): If True, skip lines starting with import/from.

    Returns:
        dict: score_bins mapping category to counts and lines.
        list of dict: detailed info for each parsed line.
    """
    # Define bins: lower score == more C (better)
    score_bins = {
        "excellent": {"range": (0, 0), "count": 0, "lines": []},
        "good": {"range": (1, 19), "count": 0, "lines": []},
        "yellow": {"range": (20, 39), "count": 0, "lines": []},
        "red": {"range": (40, 255), "count": 0, "lines": []},
    }

    detailed = []

    # Regex to match annotated source lines
    line_re = re.compile(
        r'<pre class=["\']cython line score-(\d+)["\'][^>]*>'  # score
        r"(\+?)"  # clickable flag
        r"<span[^>]*>(\d+)</span>:"  # line number
        r"(.*?)</pre>",  # source text
        re.DOTALL,
    )

    for match in line_re.finditer(html_content):
        score = int(match.group(1))
        plus = bool(match.group(2))
        lineno = int(match.group(3))
        source = match.group(4).strip()

        # Skip imports if requested
        if ignore_imports and source.startswith(("import ", "from ")):
            continue

        # Skip outside hot_ranges
        if hot_ranges and not any(start <= lineno <= end for start, end in hot_ranges):
            continue

        # Find matching C code block (the next <pre class='cython code ...'>)
        c_code = None
        # Build a minimal per-score code-block regex
        code_re = re.compile(
            rf"<pre class=[\'\"]cython code score-{score}[^>]*>(.*?)</pre>", re.DOTALL
        )
        code_match = code_re.search(html_content, match.end())
        if code_match:
            c_code = code_match.group(1)

        # Assign to bins
        for cat, info in score_bins.items():
            lo, hi = info["range"]
            if lo <= score <= hi:
                info["count"] += 1
                info["lines"].append((lineno, source))
                break

        # Collect detailed info
        detail = {
            "lineno": lineno,
            "score": score,
            "source": source,
            "exception_overhead": 0,
            "api_calls": 0,
        }
        if c_code:
            # Count exception handling overhead indicators
            detail["exception_overhead"] = c_code.count("__PYX_ERR") + c_code.count(
                "error_goto"
            )
            # Count Python C-API calls patterns
            detail["api_calls"] = len(re.findall(r"__Pyx_PyObject", c_code))
        detailed.append(detail)

    # Compute percentages
    total = sum(info["count"] for info in score_bins.values())
    for info in score_bins.values():
        info["percentage"] = round(100.0 * info["count"] / total, 1) if total else 0.0

    return score_bins, detailed


def ensure_cython_compilation(src_dir):
    """Ensure Cython compilation works by adding helper files when needed."""
    logger.info("Setting up Cython compilation helpers...")

    # Check all .pyx files to detect import patterns
    import_patterns = {
        "numpy": False,
        "pandas": False,
        "scipy": False,
        "cython.parallel": False,
        "openmp": False,
    }

    pyx_files = []
    for root, _, files in os.walk(src_dir):
        for fn in files:
            if fn.endswith(".pyx"):
                pyx_files.append(os.path.join(root, fn))
                file_path = os.path.join(root, fn)
                with open(file_path, "r") as f:
                    content = f.read()
                    # Check for import patterns
                    if "import numpy" in content or "cimport numpy" in content:
                        import_patterns["numpy"] = True
                    if "import pandas" in content or "cimport pandas" in content:
                        import_patterns["pandas"] = True
                    if "import scipy" in content or "cimport scipy" in content:
                        import_patterns["scipy"] = True
                    if "cython.parallel" in content:
                        import_patterns["cython.parallel"] = True
                    if "openmp" in content:
                        import_patterns["openmp"] = True

    if not pyx_files:
        logger.info("No .pyx files found, nothing to compile")
        return False

    logger.info(f"Detected dependencies: {import_patterns}")

    # Create setup.py with proper include paths for detected imports
    setup_py = os.path.join(src_dir, "setup.py")
    with open(setup_py, "w") as f:
        f.write("""
from setuptools import setup, Extension, find_packages
from Cython.Build import cythonize
import os
import sys

# Helper to get include directories for various packages
def get_include_dirs():
    include_dirs = []
    
    # Add NumPy include path if available
    try:
        import numpy
        include_dirs.append(numpy.get_include())
        print("Added NumPy include path")
    except ImportError:
        pass
    
    # Add Pandas include path if available
    try:
        import pandas
        pandas_path = os.path.dirname(pandas.__file__)
        include_dirs.append(os.path.join(pandas_path, 'src', 'include'))
        print("Added Pandas include path")
    except ImportError:
        pass
    
    # Add Python include path
    include_dirs.append(os.path.dirname(os.path.dirname(os.__file__)))
    
    return include_dirs

# Find all .pyx files in this directory and subdirectories
pyx_files = []
for root, _, files in os.walk('.'):
    for file in files:
        if file.endswith('.pyx'):
            pyx_path = os.path.join(root, file)
            # Convert to module name
            module_path = os.path.splitext(pyx_path)[0].replace(os.path.sep, '.')
            if module_path.startswith('.'):
                module_path = module_path[1:]
            pyx_files.append(pyx_path)

print(f"Found .pyx files: {pyx_files}")

# Define compiler arguments based on detected imports
extra_compile_args = []
extra_link_args = []

# OpenMP support if needed
use_openmp = False
try:
    with open('openmp_check.c', 'w') as f:
        f.write('#include <omp.h>\\nint main() { return 0; }\\n')
    if os.system('gcc -fopenmp -o openmp_check openmp_check.c 2>/dev/null') == 0:
        use_openmp = True
        extra_compile_args.append('-fopenmp')
        extra_link_args.append('-fopenmp')
        print("OpenMP support enabled")
    if os.path.exists('openmp_check'):
        os.remove('openmp_check')
    if os.path.exists('openmp_check.c'):
        os.remove('openmp_check.c')
except:
    pass

# Create extensions
extensions = []
for pyx_file in pyx_files:
    module_name = os.path.splitext(pyx_file)[0].replace(os.path.sep, '.')
    if module_name.startswith('.'):
        module_name = module_name[1:]
    
    extensions.append(
        Extension(
            module_name,
            [pyx_file],
            include_dirs=get_include_dirs(),
            extra_compile_args=extra_compile_args,
            extra_link_args=extra_link_args,
        )
    )

# Cython compiler directives
compiler_directives = {
    'language_level': 3,  # Python 3 support
    'boundscheck': False,  # Disable bounds checking for better performance
    'wraparound': False,  # Disable negative indexing for better performance
    'initializedcheck': False,  # Skip checks if memory views are initialized
    'embedsignature': True,  # Include docstring signatures
    'binding': True,  # Generate binding code for Python classes
}

# Finally, set up the extension modules
setup(
    ext_modules=cythonize(
        extensions,
        compiler_directives=compiler_directives,
        annotate=True  # Generate HTML annotation
    )
)
""")

    # Create pyproject.toml for modern Python packaging
    pyproject_toml = os.path.join(src_dir, "pyproject.toml")
    with open(pyproject_toml, "w") as f:
        f.write("""
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython>=0.29.21"
]
""")

        # Add numpy requirement if detected
        if import_patterns["numpy"]:
            f.write('    "numpy>=1.10",\n')

        # Add pandas requirement if detected
        if import_patterns["pandas"]:
            f.write('    "pandas>=1.0",\n')

        # Add scipy requirement if detected
        if import_patterns["scipy"]:
            f.write('    "scipy>=1.0",\n')

        f.write('build-backend = "setuptools.build_meta"\n')

    logger.info("Created setup.py and pyproject.toml with appropriate dependencies")
    return True


def compile_and_annotate(src_dir):
    logger.info(f"Compiling and annotating code in {src_dir}")

    # Save code content and perform manual analysis
    pyx_code = {}
    manual_yellow_lines = []
    manual_red_lines = []

    for root, _, files in os.walk(src_dir):
        for fn in files:
            if fn.endswith(".pyx"):
                file_path = os.path.join(root, fn)
                with open(file_path, "r") as f:
                    code = f.read()
                    pyx_code[fn] = code
                    logger.info(f"Code content of {fn}:\n{code}")

                    # Perform manual analysis
                    y_lines, r_lines = analyze_cython_efficiency(code)
                    manual_yellow_lines.extend([(fn, ln, line) for ln, line in y_lines])
                    manual_red_lines.extend([(fn, ln, line) for ln, line in r_lines])

    # First attempt: direct cythonize
    cythonize_success = False
    html_files_found = False

    try:
        logger.info("Attempting direct cythonize compilation...")
        result = subprocess.run(
            [
                "cythonize",
                "--depfile",
                "--annotate",
                "-i",
                "-3",  # Force Python 3 mode
                "-a",  # More detailed annotations
                src_dir,
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        logger.info(f"Cythonize output: {result.stdout}")
        if result.stderr:
            logger.warning(f"Cythonize stderr: {result.stderr}")

        # Check if HTML files were generated
        for root, _, files in os.walk(src_dir):
            if any(fn.endswith(".html") for fn in files):
                html_files_found = True
                break

        if html_files_found:
            cythonize_success = True
            logger.info("Direct cythonize succeeded with HTML annotation files")
        else:
            logger.warning(
                "Direct cythonize didn't produce HTML files, trying alternative method"
            )
    except subprocess.CalledProcessError as e:
        logger.warning(f"Direct cythonize failed: {e}")
        logger.warning(f"Stdout: {e.stdout}")
        logger.warning(f"Stderr: {e.stderr}")

    # Second attempt: Use setup.py approach if direct cythonize failed
    if not cythonize_success:
        logger.info("Setting up alternative compilation approach with setup.py")
        ensure_cython_compilation(src_dir)

        try:
            logger.info("Compiling with setup.py...")
            setup_result = subprocess.run(
                [
                    sys.executable,
                    os.path.join(src_dir, "setup.py"),
                    "build_ext",
                    "--inplace",
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            logger.info(f"Setup.py build output: {setup_result.stdout}")
            if setup_result.stderr:
                logger.warning(f"Setup.py stderr: {setup_result.stderr}")

            # Check again if HTML files were generated
            for root, _, files in os.walk(src_dir):
                if any(fn.endswith(".html") for fn in files):
                    html_files_found = True
                    break

            if html_files_found:
                cythonize_success = True
                logger.info("Setup.py build succeeded with HTML annotation files")
            else:
                logger.warning("Setup.py build didn't produce HTML files")
        except subprocess.CalledProcessError as e:
            logger.error(f"Setup.py build failed: {e}")
            logger.error(f"Stdout: {e.stdout}")
            logger.error(f"Stderr: {e.stderr}")

            # Third attempt: Fallback to minimal compilation without annotations
            try:
                logger.info("Attempting minimal compilation without annotations...")
                with open(os.path.join(src_dir, "setup.py"), "w") as f:
                    f.write("""
from setuptools import setup, Extension
from Cython.Build import cythonize
import os, sys

# Find all .pyx files
pyx_files = []
for root, _, files in os.walk('.'):
    for file in files:
        if file.endswith('.pyx'):
            pyx_path = os.path.join(root, file)
            pyx_files.append(pyx_path)

# Create minimal extensions
extensions = [
    Extension(
        os.path.splitext(pyx_file)[0].replace(os.path.sep, '.').lstrip('.'),
        [pyx_file],
        extra_compile_args=["-w"]  # Disable warnings
    ) for pyx_file in pyx_files
]

setup(ext_modules=cythonize(extensions, language_level=3, annotate=True))
""")

                minimal_result = subprocess.run(
                    [
                        sys.executable,
                        os.path.join(src_dir, "setup.py"),
                        "build_ext",
                        "--inplace",
                    ],
                    check=True,
                    capture_output=True,
                    text=True,
                )
                logger.info(f"Minimal compilation output: {minimal_result.stdout}")

                # No HTML files but at least we compiled the code
                logger.warning(
                    "Compiled without annotations - will use manual analysis only"
                )
            except subprocess.CalledProcessError as e:
                logger.error(f"All compilation attempts failed: {e}")
                raise RuntimeError(
                    "Unable to compile Cython code after multiple attempts"
                )

    # Process HTML files and extract scores if available
    total_yellow = 0
    total_red = 0
    html_contents = {}
    html_analysis_yellow = []
    html_analysis_red = []
    detailed_html_analysis = {}

    if html_files_found:
        logger.info(f"Searching for HTML annotation files in {src_dir}")
        for root, _, files in os.walk(src_dir):
            for fn in files:
                if fn.endswith(".html"):
                    file_path = os.path.join(root, fn)
                    logger.info(f"Processing HTML file: {file_path}")

                    try:
                        with open(file_path, "r") as f:
                            html_content = f.read()

                        # Save HTML content
                        html_contents[fn] = html_content

                        # Parse Cython HTML for scores and inefficient lines
                        score_bins, detailed = parse_cython_html(html_content)

                        # Format detailed analysis data
                        file_detailed_analysis = {
                            "score_distribution": score_bins,
                            "efficiency_metrics": {
                                "avg_score": sum(d["score"] for d in detailed)
                                / len(detailed)
                                if detailed
                                else 0,
                                "python_api_heavy_lines": sum(
                                    1 for d in detailed if d["api_calls"] > 0
                                ),
                                "exception_handling_lines": sum(
                                    1 for d in detailed if d["exception_overhead"] > 0
                                ),
                            },
                        }

                        # Add file information to lines
                        html_analysis_yellow.extend(
                            [
                                (fn, ln, line)
                                for ln, line in score_bins["yellow"]["lines"]
                            ]
                        )
                        html_analysis_red.extend(
                            [(fn, ln, line) for ln, line in score_bins["red"]["lines"]]
                        )

                        # Accumulate totals
                        total_yellow += score_bins["yellow"]["count"]
                        total_red += score_bins["red"]["count"]

                        # Save detailed analysis
                        detailed_html_analysis[fn] = file_detailed_analysis

                        logger.info(
                            f"Found {score_bins['yellow']['count']} yellow lines and {score_bins['red']['count']} red lines in {fn}"
                        )
                    except Exception as e:
                        logger.error(f"Error processing HTML file {file_path}: {e}")

    if not html_files_found:
        logger.warning(
            "No HTML annotation files were found! Using manual analysis only."
        )
        # List all files in directory for debugging
        all_files = []
        for root, _, files in os.walk(src_dir):
            for f in files:
                all_files.append(os.path.join(root, f))
        logger.info(f"Files in directory: {all_files}")

    # Log manual analysis results
    logger.info(
        f"Manual analysis: {len(manual_yellow_lines)} yellow lines, {len(manual_red_lines)} red lines"
    )
    for fn, line_num, line in manual_yellow_lines[:10]:  # Log first 10 for brevity
        logger.info(f"Yellow line {fn}:{line_num}: {line}")
    for fn, line_num, line in manual_red_lines[:10]:
        logger.info(f"Red line {fn}:{line_num}: {line}")

    # Combine HTML analysis with manual analysis if HTML results are sparse
    if html_files_found and (total_yellow + total_red > 0):
        logger.info(
            f"Using HTML analysis: {total_yellow} yellow lines and {total_red} red lines"
        )
        yellow = total_yellow
        red = total_red
        # Use HTML analysis for detailed line info if available
        if len(html_analysis_yellow) > 0 or len(html_analysis_red) > 0:
            combined_yellow = html_analysis_yellow
            combined_red = html_analysis_red
        else:
            combined_yellow = manual_yellow_lines
            combined_red = manual_red_lines
    else:
        logger.info(
            f"Using manual analysis: {len(manual_yellow_lines)} yellow lines and {len(manual_red_lines)} red lines"
        )
        yellow = len(manual_yellow_lines)
        red = len(manual_red_lines)
        combined_yellow = manual_yellow_lines
        combined_red = manual_red_lines

    return (
        yellow,
        red,
        html_contents,
        combined_yellow,
        combined_red,
        detailed_html_analysis,
    )


def run_linters(src_dir):
    logger.info(f"Running linters on {src_dir}")

    # Cython-lint
    try:
        lint_result = subprocess.run(
            ["cython-lint", src_dir], capture_output=True, text=True
        )
        lint_issues = lint_result.stdout.count("\n")
        if lint_result.stderr:
            logger.warning(f"Cython-lint stderr: {lint_result.stderr}")
        logger.info(f"Found {lint_issues} Cython lint issues")
    except Exception as e:
        logger.error(f"Error running cython-lint: {e}")
        lint_issues = 0

    # PEP8 via flake8
    try:
        pep8_result = subprocess.run(
            ["flake8", src_dir], capture_output=True, text=True
        )
        pep8_issues = pep8_result.stdout.count("\n")
        if pep8_result.stderr:
            logger.warning(f"flake8 stderr: {pep8_result.stderr}")
        logger.info(f"Found {pep8_issues} PEP8 issues")
    except Exception as e:
        logger.error(f"Error running flake8: {e}")
        pep8_issues = 0

    return lint_issues, pep8_issues


def handle_job(job_file_path, output_dir):
    # Fix job ID extraction - remove .tar if present
    job_id = Path(job_file_path).stem
    if job_id.endswith(".tar"):
        job_id = job_id[:-4]

    result_file = os.path.join(output_dir, f"{job_id}.json")
    html_dir = os.path.join(output_dir, "html")
    os.makedirs(html_dir, exist_ok=True)

    # Already processed?
    if os.path.exists(result_file):
        logger.info(f"Job {job_id} already processed, skipping")
        return

    logger.info(f"Processing job {job_id} from {job_file_path}")

    # 1) Unpack into a temp workspace
    workdir = tempfile.mkdtemp(prefix="job-")
    logger.info(f"Created temp workspace at {workdir}")

    try:
        # Extract tarball
        extract_cmd = ["tar", "xzf", job_file_path, "-C", workdir]
        logger.info(f"Extracting with command: {' '.join(extract_cmd)}")
        extract_result = subprocess.run(
            extract_cmd, check=True, capture_output=True, text=True
        )
        if extract_result.stdout:
            logger.info(f"Extraction stdout: {extract_result.stdout}")
        if extract_result.stderr:
            logger.info(f"Extraction stderr: {extract_result.stderr}")

        # List files in workdir
        files_in_workdir = os.listdir(workdir)
        logger.info(f"Files in workspace: {files_in_workdir}")

        # ─── Insert minimal TOML for cython-lint here ─────────────────────────
        toml_path = os.path.join(workdir, "pyproject.toml")
        logger.info(f"Writing minimal TOML config to {toml_path}")
        with open(toml_path, "w") as f:
            f.write("[tool.cython-lint]\n")

        # 2) Compile & annotate
        yellow, red, html_contents, yellow_lines, red_lines, detailed_analysis = (
            compile_and_annotate(workdir)
        )

        # 3) Lint checks
        lint_issues, pep8_issues = run_linters(workdir)

        # 4) Save HTML files
        saved_html_files = []
        for filename, content in html_contents.items():
            html_file_name = f"{job_id}_{filename}"
            html_file_path = os.path.join(html_dir, html_file_name)
            with open(html_file_path, "w") as f:
                f.write(content)
            saved_html_files.append(html_file_name)
            logger.info(f"Saved HTML file: {html_file_path}")

        # 5) Create result
        result = {
            "job_id": job_id,
            "yellow_lines": yellow,
            "red_lines": red,
            "cython_lint": lint_issues,
            "pep8_issues": pep8_issues,
            "timestamp": time.time(),
            "status": "completed",
            "html_files": saved_html_files,
            "manual_analysis": {
                "yellow_lines": [
                    {"file": fn, "line_num": ln, "content": line}
                    for fn, ln, line in yellow_lines
                ],
                "red_lines": [
                    {"file": fn, "line_num": ln, "content": line}
                    for fn, ln, line in red_lines
                ],
            },
            "detailed_analysis": detailed_analysis,
        }

        # Write to output file
        logger.info(f"Writing results to {result_file}")
        with open(result_file, "w") as f:
            json.dump(result, f)

        logger.info(f"Completed job {job_id}")
        logger.info(f"Results: {json.dumps(result)}")

    except Exception as e:
        logger.error(f"Error processing job {job_id}: {e}", exc_info=True)
        # Log the error result
        error_result = {
            "job_id": job_id,
            "error": str(e),
            "timestamp": time.time(),
            "status": "error",
            "yellow_lines": 0,
            "red_lines": 0,
            "cython_lint": 0,
            "pep8_issues": 0,
        }
        logger.info(f"Writing error results to {result_file}")
        with open(result_file, "w") as f:
            json.dump(error_result, f)

    finally:
        # 6) Clean up
        logger.info(f"Cleaning up workspace {workdir}")
        shutil.rmtree(workdir)


def main():
    # Parse arguments
    parser = argparse.ArgumentParser(description="Cython worker service")
    parser.add_argument(
        "--job-dir", default=JOB_DIRECTORY, help="Directory to watch for jobs"
    )
    parser.add_argument(
        "--output-dir", default=OUTPUT_DIRECTORY, help="Directory for results"
    )
    parser.add_argument(
        "--poll-interval",
        type=int,
        default=POLLING_INTERVAL,
        help="Polling interval in seconds",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true", help="Enable verbose logging"
    )
    args = parser.parse_args()

    # Configure logging level
    if args.verbose:
        logger.setLevel(logging.DEBUG)

    # Ensure directories exist
    os.makedirs(args.job_dir, exist_ok=True)
    os.makedirs(args.output_dir, exist_ok=True)
    os.makedirs(os.path.join(args.output_dir, "html"), exist_ok=True)
    archive_dir = os.path.join(args.job_dir, "archive")
    os.makedirs(archive_dir, exist_ok=True)

    logger.info(
        f"Cython worker service started. Watching {args.job_dir} for .tar.gz files"
    )

    # Set up signal handlers for graceful shutdown
    running = True

    def signal_handler(sig, frame):
        nonlocal running
        logger.info("Shutdown signal received, finishing current job...")
        running = False

    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)

    # Main service loop
    while running:
        # Find all .tar.gz files in the job directory
        job_files = [f for f in os.listdir(args.job_dir) if f.endswith(".tar.gz")]

        if job_files:
            logger.info(f"Found {len(job_files)} job files: {job_files}")

        for job_file in job_files:
            job_path = os.path.join(args.job_dir, job_file)
            try:
                handle_job(job_path, args.output_dir)

                # Move processed files to archive directory
                archive_path = os.path.join(archive_dir, job_file)
                logger.info(f"Moving processed job {job_file} to archive")
                shutil.move(job_path, archive_path)
            except Exception as e:
                logger.error(
                    f"Unhandled exception processing {job_file}: {e}", exc_info=True
                )

        # Sleep before next check
        time.sleep(args.poll_interval)

    logger.info("Worker service shutting down")


if __name__ == "__main__":
    main()
