# cython: boundscheck=False, wraparound=False, cdivision=True, language_level=3
"""Flip generated byte-image rows and convert pixels to normalized values (Cython).

Adapted from The Stack v2 Cython candidate:
- blob_id: 1846657d33ecd757445eefdf38ac496f4535ef10
- filename: converter.pyx
"""

from libc.stdlib cimport malloc, free
from cnake_data.benchmarks import cython_benchmark


cdef void _fill_data(unsigned char* data, int size, unsigned int* state) noexcept nogil:
    cdef int i
    cdef unsigned int mask = 0xFFFFFFFF
    for i in range(size):
        state[0] = (1664525 * state[0] + 1013904223) & mask
        data[i] = <unsigned char>((state[0] >> 16) & 0xFF)


cdef long long _flip_and_sum(
    unsigned char* data,
    unsigned char* flipped,
    int width,
    int height,
    int channels,
) noexcept nogil:
    cdef int row_size = width * channels
    cdef int y, j, src, dst
    cdef long long out = 0
    for y in range(height):
        src = (height - 1 - y) * row_size
        dst = y * row_size
        for j in range(row_size):
            flipped[dst + j] = data[src + j]
            out += flipped[dst + j]
    return out


cdef unsigned int _checksum(unsigned char* flipped, int size) noexcept nogil:
    cdef int i
    cdef unsigned int checksum = 0
    cdef unsigned int mask = 0xFFFFFFFF
    for i in range(size):
        checksum = (checksum + <unsigned int>((i + 1) * flipped[i])) & mask
    return checksum


@cython_benchmark(syntax="cy", args=(256, 192, 3))
def stack_byte_flip_convert(int width, int height, int channels):
    cdef int size = width * height * channels
    cdef unsigned int state = 2463534242
    cdef unsigned char *data = <unsigned char *>malloc(size * sizeof(unsigned char))
    cdef unsigned char *flipped = <unsigned char *>malloc(size * sizeof(unsigned char))
    cdef int first = 0
    cdef int last = 0
    cdef long long out = 0
    cdef unsigned int checksum = 0

    if not data or not flipped:
        free(data)
        free(flipped)
        raise MemoryError()

    with nogil:
        _fill_data(data, size, &state)
        out = _flip_and_sum(data, flipped, width, height, channels)
        checksum = _checksum(flipped, size)

    if size > 0:
        first = flipped[0]
        last = flipped[size - 1]

    free(data)
    free(flipped)
    return (out, first, last, checksum)
