"""
Build SFT dataset from collected trace files using sft_scoring for selection.

Loads traces from data/traces/*.jsonl, re-scores with sft_scoring.score_trace(),
augments with problem inputs from discover_pairs(), selects best per problem,
renders to Harmony format, validates, and saves.

Rendered Data Format (Harmony):
    PREAMBLE (3 messages):
        system   — auto-generated by template: identity, Reasoning: {effort}, channels
        developer — our custom system prompt (data/system_prompt.txt) + tool schemas
        user     — problem input (python_code, func_name, description)

    BODY (1+ turn groups, each 2-3 messages):
        [optional] assistant analysis  — reasoning/planning content
        assistant→functions.{tool}     — tool call with JSON args, ends <|call|>
        functions.{tool}→assistant     — tool response, ends <|end|>

    TERMINAL: Last message is always a tool response (never standalone assistant).

    Reasoning effort assigned by rendered analysis length terciles:
        bottom third → low, middle third → medium, top third → high

    See cnake_charmer/training/sft_validation.py for full specification.

Usage:
    uv run --no-sync python scripts/build_sft.py --require-finish --min-iters 2
    uv run --no-sync python scripts/build_sft.py --min-score 0.5 --output data/sft_dataset.jsonl
"""

import argparse
import json
import logging
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from cnake_charmer.traces.io import load_traces as _load_traces
from cnake_charmer.traces.models import Trace
from cnake_charmer.training.sft_scoring import parse_trace_metrics, score_trace
from cnake_charmer.training.sft_validation import (
    total_analysis_length,
    validate_rendered_example,
    validate_trace_for_rendering,
)
from cnake_data.loader import discover_pairs

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

TRACES_DIR = Path("data/traces")
MASTER_FILES = [TRACES_DIR / "master_traces.jsonl"]
TOOLS_FILE = Path("data/tools.json")
SYSTEM_PROMPT_FILE = Path("data/system_prompt.txt")


def main():
    parser = argparse.ArgumentParser(description="Build SFT dataset from trace files")
    parser.add_argument(
        "--inputs",
        "-i",
        nargs="+",
        default=None,
        help="Input JSONL trace files (default: all data/traces/*.jsonl)",
    )
    parser.add_argument(
        "--output",
        "-o",
        default="data/sft_dataset.jsonl",
        help="Output JSONL path (default: data/sft_dataset.jsonl)",
    )
    parser.add_argument(
        "--min-score", type=float, default=0.8, help="Minimum sft_score to include (default: 0.8)"
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=1,
        help="Keep top-k traces per problem above threshold (default: 1)",
    )
    parser.add_argument(
        "--tools", default=str(TOOLS_FILE), help=f"Tool schema JSON file (default: {TOOLS_FILE})"
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=16384,
        help="Max tokens per example; truncate reasoning then drop (default: 16384)",
    )
    parser.add_argument(
        "--min-iters",
        type=int,
        default=0,
        help="Minimum tool-call iterations to include (default: 0, no filter)",
    )
    parser.add_argument(
        "--require-finish",
        action="store_true",
        help="Only include traces that called finish (exclude force-exits)",
    )
    args = parser.parse_args()

    input_paths = args.inputs or [str(p) for p in MASTER_FILES if p.exists()]

    # Load problems for inputs augmentation
    logger.info("Loading problems...")
    problems = {p.problem_id: p for p in discover_pairs()}
    logger.info(f"  {len(problems)} problems loaded")

    # Load tools
    tools = None
    tools_path = Path(args.tools)
    if tools_path.exists():
        tools = json.loads(tools_path.read_text())
        logger.info(f"Loaded {len(tools)} tool schemas from {tools_path}")
    else:
        logger.warning(f"No tools file at {tools_path} — 'tools' column will be omitted")

    # Load all traces (v2 Trace objects)
    logger.info("Loading traces...")
    traces = _load_traces(input_paths)
    logger.info(f"Total: {len(traces)} traces")

    # Score and augment with inputs
    logger.info("Scoring and augmenting traces...")
    scored: list[tuple[Trace, float, dict]] = []  # (trace, sft_score, inputs)
    skipped_no_problem = 0
    skipped_no_finish = 0
    skipped_min_iters = 0
    for trace in traces:
        sft = score_trace(trace)
        if sft < args.min_score:
            continue

        # Filter: require finish tool call
        if args.require_finish and not any(s.tool_name == "finish" for s in trace.steps):
            skipped_no_finish += 1
            continue

        # Filter: minimum iterations (eval calls excluding finish)
        if args.min_iters > 0:
            n_evals = sum(1 for s in trace.steps if s.tool_name != "finish")
            if n_evals < args.min_iters:
                if n_evals == 1 and sft >= 0.9:
                    pass  # keep it — model nailed it first try
                else:
                    skipped_min_iters += 1
                    continue

        problem = problems.get(trace.problem_id)
        if problem is None:
            skipped_no_problem += 1
            continue

        trace.reward = sft
        inputs = {
            "python_code": problem.python_code,
            "func_name": problem.func_name,
            "description": problem.description or "",
            "test_cases": problem.test_cases,
            "benchmark_args": problem.benchmark_args,
        }
        scored.append((trace, sft, inputs))

    logger.info(
        f"  {len(scored)} traces passed (skipped {skipped_no_problem} unknown problem_ids, "
        f"{skipped_no_finish} no finish, {skipped_min_iters} too few iters)"
    )

    # Trace-level validation: reject traces with malformed tool args before rendering
    # validate_trace_for_rendering expects v1 dicts
    valid_scored = []
    skipped_validation = 0
    for trace, sft, inputs in scored:
        v1 = trace.to_v1_dict()
        errs = validate_trace_for_rendering(v1)
        if errs:
            skipped_validation += 1
            logger.debug(f"  Trace validation failed ({trace.problem_id}): {errs[0]}")
            continue
        valid_scored.append((trace, sft, inputs))
    if skipped_validation:
        logger.info(f"  Trace validation: dropped {skipped_validation} traces with malformed data")
    scored = valid_scored

    # Step 1: best per (problem, model, thinking) — deduplicate
    by_key: dict[tuple, tuple[Trace, float, dict]] = {}
    for trace, sft, inputs in scored:
        key = (trace.problem_id, trace.model, trace.thinking)
        if key not in by_key or sft > by_key[key][1]:
            by_key[key] = (trace, sft, inputs)

    # Step 2: top-k per problem per thinking split, unique models
    thinking_pool: dict[str, list[tuple[Trace, float, dict]]] = defaultdict(list)
    nothink_pool: dict[str, list[tuple[Trace, float, dict]]] = defaultdict(list)
    for (pid, _model, is_thinking), entry in by_key.items():
        if is_thinking:
            thinking_pool[pid].append(entry)
        else:
            nothink_pool[pid].append(entry)

    best: list[tuple[Trace, float, dict]] = []
    all_pids = sorted(set(list(thinking_pool.keys()) + list(nothink_pool.keys())))
    for pid in all_pids:
        for pool in (thinking_pool, nothink_pool):
            candidates = pool.get(pid, [])
            ranked = sorted(candidates, key=lambda e: e[1], reverse=True)
            best.extend(ranked[: args.top_k])

    problems_covered = len(all_pids)
    n_thinking = sum(1 for t, _, _ in best if t.thinking)
    n_nothink = len(best) - n_thinking
    logger.info(
        f"Top-{args.top_k} selection: {len(best)} examples from {problems_covered} problems"
    )
    logger.info(f"  thinking={n_thinking}, nothink={n_nothink}")

    # Per-model breakdown
    raw_counts = Counter(t.model for t in traces)
    sel_models = defaultdict(lambda: {"total": 0, "think": 0, "nothink": 0})
    for t, _, _ in best:
        sel_models[t.model]["total"] += 1
        sel_models[t.model]["think" if t.thinking else "nothink"] += 1

    logger.info("Per-model breakdown:")
    logger.info(
        f"  {'Model':<35} {'Traces':>6} {'Accept':>6} {'Rate':>5} {'Think':>5} {'NoThk':>5}"
    )
    for model in sorted(sel_models, key=lambda m: raw_counts[m], reverse=True):
        s = sel_models[model]
        r = raw_counts[model]
        rate = f"{s['total'] / r * 100:.0f}%" if r > 0 else "-"
        name = model.replace("openrouter/", "").replace("openai/", "")
        logger.info(
            f"  {name:<35} {r:>6} {s['total']:>6} {rate:>5} {s['think']:>5} {s['nothink']:>5}"
        )

    # Load system prompt and tokenizer for Harmony rendering
    system_prompt = None
    if SYSTEM_PROMPT_FILE.exists():
        system_prompt = SYSTEM_PROMPT_FILE.read_text().strip()
        logger.info(f"Loaded system prompt ({len(system_prompt)} chars)")
    else:
        logger.warning(f"No system prompt at {SYSTEM_PROMPT_FILE}")

    from transformers import AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained("openai/gpt-oss-20b")

    # Build messages and render to Harmony text.
    # Key design decisions:
    # - Thinking traces: reasoning_N for analysis channel (deep reasoning)
    # - Nothink traces: thought_N for analysis channel (brief planning)
    # - NO final standalone code message — end with finish tool call so all analysis channels render
    #   (Harmony template drops analysis when a future non-tool-call assistant message exists)
    # - Reasoning effort assigned AFTER rendering by analysis length terciles (see below)

    def _generate_test_code(func_name, test_cases):
        """Generate py/cy equivalence test code from test_cases.

        Transforms [((10,),), ((100,),)] into:
            py.func(10) == cy.func(10)
            py.func(100) == cy.func(100)
        """
        lines = []
        for tc in test_cases or []:
            if isinstance(tc, (list, tuple)) and len(tc) >= 1:
                args = tc[0] if isinstance(tc[0], (list, tuple)) else tc
                args_str = ", ".join(repr(a) for a in args)
                lines.append(f"py.{func_name}({args_str}) == cy.{func_name}({args_str})")
        return "\n".join(lines)

    def build_messages(trace, system_prompt):
        """Build OpenAI-format messages from a trace for Harmony rendering."""
        traj = trace.get("trajectory", {})
        is_thinking = trace.get("_thinking", False)
        inputs = trace.get("inputs", {})

        # Extract python_code and test_code for the new 3-param tool format
        python_code = inputs.get("python_code", "")
        func_name = inputs.get("func_name", "")
        test_cases = inputs.get("test_cases", [])
        test_code = _generate_test_code(func_name, test_cases)

        msgs = []
        if system_prompt:
            msgs.append({"role": "system", "content": system_prompt})

        user_content = "\n".join(
            f"{k}: {v}" for k, v in inputs.items() if k not in ("test_cases", "benchmark_args")
        )
        msgs.append({"role": "user", "content": user_content})

        n_iters = trace.get("num_iterations", 0)
        for i in range(n_iters):
            tool_name = traj.get(f"tool_name_{i}")
            tool_args = traj.get(f"tool_args_{i}", {})
            observation = traj.get(f"observation_{i}", "")

            if not tool_name:
                continue

            # Transform tool args to new 3-param format
            if isinstance(tool_args, str):
                try:
                    tool_args = json.loads(tool_args)
                except (json.JSONDecodeError, TypeError):
                    tool_args = {}
            if isinstance(tool_args, dict) and "code" in tool_args:
                # Keep only the 3 required params, drop old bools
                tool_args = {
                    "code": tool_args["code"],
                    "python_code": python_code,
                    "test_code": test_code,
                }

            # Select reasoning for analysis channel
            if is_thinking:
                reasoning = traj.get(f"reasoning_{i}", "")
                reasoning = reasoning.replace("<think>\n", "").replace("\n</think>", "").strip()
                if not reasoning:
                    reasoning = traj.get(f"thought_{i}", "")
            else:
                reasoning = traj.get(f"thought_{i}", "")

            assistant_msg = {
                "role": "assistant",
                "tool_calls": [
                    {
                        "id": f"call_{i}",
                        "type": "function",
                        "function": {
                            "name": tool_name,
                            "arguments": tool_args if tool_args else {},
                        },
                    }
                ],
            }
            if reasoning:
                assistant_msg["content"] = reasoning

            msgs.append(assistant_msg)
            msgs.append(
                {
                    "role": "tool",
                    "tool_call_id": f"call_{i}",
                    "name": tool_name,
                    "content": observation,
                }
            )

        return msgs

    # Phase 1: Render all examples with placeholder effort ("medium")
    # Convert Trace objects to v1 dicts for build_messages (Harmony rendering reads flat trajectory)
    rendered = []
    for trace, sft, inputs in best:
        v1 = trace.to_v1_dict()
        v1["inputs"] = inputs
        v1["_thinking"] = trace.thinking
        msgs = build_messages(v1, system_prompt)

        text = tokenizer.apply_chat_template(
            msgs,
            tools=tools,
            tokenize=False,
            reasoning_effort="medium",
        )

        record = {
            "text": text,
            "model": trace.model,
            "prompt_id": trace.prompt_id,
            "problem_id": trace.problem_id,
            "func_name": trace.func_name,
            "category": trace.category,
            "difficulty": trace.difficulty,
            "num_iterations": trace.num_iterations,
            "sft_score": sft,
            "speedup": parse_trace_metrics(trace).get("speedup", 0.0),
            "thinking": trace.thinking,
        }
        rendered.append(record)

    # Phase 2: Assign reasoning effort by rendered analysis length terciles
    analysis_lens = [(i, total_analysis_length(r["text"])) for i, r in enumerate(rendered)]
    analysis_lens.sort(key=lambda x: x[1])
    n = len(analysis_lens)
    tercile_1 = n // 3
    tercile_2 = 2 * n // 3

    for rank, (idx, _length) in enumerate(analysis_lens):
        if rank < tercile_1:
            effort = "low"
        elif rank < tercile_2:
            effort = "medium"
        else:
            effort = "high"

        rendered[idx]["reasoning_effort"] = effort
        # Patch the system message in-place
        rendered[idx]["text"] = rendered[idx]["text"].replace(
            "Reasoning: medium", f"Reasoning: {effort}"
        )

    # Log effort distribution with analysis length ranges
    effort_ranges = defaultdict(list)
    for r in rendered:
        effort_ranges[r["reasoning_effort"]].append(total_analysis_length(r["text"]))
    for eff in ("low", "medium", "high"):
        lens = sorted(effort_ranges.get(eff, []))
        if lens:
            logger.info(
                f"  Effort '{eff}' (n={len(lens)}): "
                f"analysis chars min={lens[0]}, p50={lens[len(lens) // 2]}, max={lens[-1]}"
            )

    # Phase 3: Validate all rendered examples against format specification
    valid = []
    n_invalid = 0
    for record in rendered:
        errs = validate_rendered_example(record["text"], record)
        if errs:
            n_invalid += 1
            logger.warning(
                f"  Validation failed ({record.get('problem_id')}): {errs[0]}"
                + (f" (+{len(errs) - 1} more)" if len(errs) > 1 else "")
            )
        else:
            valid.append(record)
    if n_invalid:
        logger.info(f"  Validation: dropped {n_invalid}/{len(rendered)} invalid examples")

    examples = valid
    logger.info(f"Rendered {len(examples)} valid examples to Harmony text")

    # Token counting using the actual tokenizer
    def count_tokens(text: str) -> int:
        return len(tokenizer.encode(text))

    # Filter by token count
    kept = []
    n_dropped = 0
    for ex in examples:
        tok = count_tokens(ex["text"])
        if tok <= args.max_tokens:
            kept.append(ex)
        else:
            n_dropped += 1

    logger.info(f"Token filter (max={args.max_tokens}): kept={len(kept)}, dropped={n_dropped}")
    examples = kept

    # Token distribution stats
    if examples:
        all_tok = sorted(count_tokens(ex["text"]) for ex in examples)
        think_tok = sorted(count_tokens(ex["text"]) for ex in examples if ex.get("thinking"))
        nothink_tok = sorted(count_tokens(ex["text"]) for ex in examples if not ex.get("thinking"))
        n = len(all_tok)

        def pct(data, p):
            return data[min(int(p / 100 * len(data)), len(data) - 1)] if data else 0

        logger.info(
            f"Tokens (all n={n}): "
            f"p50={pct(all_tok, 50)}, p90={pct(all_tok, 90)}, "
            f"p95={pct(all_tok, 95)}, p99={pct(all_tok, 99)}, max={all_tok[-1]}"
        )
        if think_tok:
            logger.info(
                f"Tokens (thinking n={len(think_tok)}): "
                f"p50={pct(think_tok, 50)}, p90={pct(think_tok, 90)}, "
                f"p95={pct(think_tok, 95)}, max={think_tok[-1]}"
            )
        if nothink_tok:
            logger.info(
                f"Tokens (nothink n={len(nothink_tok)}): "
                f"p50={pct(nothink_tok, 50)}, p90={pct(nothink_tok, 90)}, "
                f"p95={pct(nothink_tok, 95)}, max={nothink_tok[-1]}"
            )

    # Reasoning effort distribution
    effort_counts = Counter(ex.get("reasoning_effort", "?") for ex in examples)
    logger.info(f"Reasoning effort: {dict(effort_counts)}")

    # Save
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w") as f:
        for ex in examples:
            f.write(json.dumps(ex, default=str) + "\n")

    logger.info(f"Saved to {output}")

    # Score distribution
    scores = [ex.get("sft_score", 0) for ex in examples]
    if scores:
        logger.info(
            f"SFT score: min={min(scores):.3f}, max={max(scores):.3f}, "
            f"mean={sum(scores) / len(scores):.3f}"
        )


if __name__ == "__main__":
    main()
