"""Zhang-Suen style binary skeletonization."""

from __future__ import annotations

import numpy as np

_LUT = np.array(
    [
        0,
        0,
        0,
        1,
        0,
        0,
        1,
        3,
        0,
        0,
        3,
        1,
        1,
        0,
        1,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        2,
        0,
        3,
        0,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        3,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        0,
        0,
        0,
        3,
        0,
        2,
        0,
        0,
        0,
        3,
        1,
        0,
        0,
        1,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        3,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        3,
        1,
        3,
        0,
        0,
        1,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        3,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        0,
        1,
        0,
        0,
        0,
        0,
        2,
        2,
        0,
        0,
        2,
        0,
        0,
        0,
    ],
    dtype=np.uint8,
)


def fast_skeletonize(image: np.ndarray) -> np.ndarray:
    image = np.asarray(image, dtype=np.uint8)
    nrows, ncols = image.shape[0] + 2, image.shape[1] + 2
    skeleton = np.zeros((nrows, ncols), dtype=np.uint8)
    skeleton[1:-1, 1:-1] = image
    cleaned = skeleton.copy()

    pixel_removed = True
    while pixel_removed:
        pixel_removed = False
        for pass_num in range(2):
            first_pass = pass_num == 0
            for row in range(1, nrows - 1):
                for col in range(1, ncols - 1):
                    if skeleton[row, col] == 0:
                        continue
                    idx = (
                        1 * skeleton[row - 1, col - 1]
                        + 2 * skeleton[row - 1, col]
                        + 4 * skeleton[row - 1, col + 1]
                        + 8 * skeleton[row, col + 1]
                        + 16 * skeleton[row + 1, col + 1]
                        + 32 * skeleton[row + 1, col]
                        + 64 * skeleton[row + 1, col - 1]
                        + 128 * skeleton[row, col - 1]
                    )
                    neighbors = _LUT[idx]
                    if (
                        (neighbors == 1 and first_pass)
                        or (neighbors == 2 and not first_pass)
                        or neighbors == 3
                    ):
                        cleaned[row, col] = 0
                        pixel_removed = True
            skeleton[:, :] = cleaned[:, :]

    return np.ascontiguousarray(skeleton[1:-1, 1:-1])
